### ISSUE TITLE
Tensor function Error

### ISSUE THREAD

**Issue by hdesale2408** [cozygene/TCA#16]
Hello,
 
  ###    I used TCA to identify cell-type significantly differentially methylated CpGs between two exposure groups (approximately 32 in each group).  In order to visualize the spread of data, I would like to present the methylation for each sample in either exposure group. Ideally, results should be graphically presented with a box plot or such for each significant CpG. I am trying to do this using the "tensor" function; however, I am getting an error. 

In order to generate my model, I used the following code: 

`tca.mdl.chagas.2 <- tca(X = beta.values,
                        W = out.l,
                        C1 = pheno.tca,
                        C2 = refactor.mdl.chagas$scores)`

where: 

- beta.values is a 715343 x 63 matrix containing the beta value outputs from 63 samples run on the EPIC array parsing 715343 CpG sites 
- out.l is a 63 x 6 matrix containing the estimated cell-type proportions for each of the 63 samples. 6 cell types were estimated 
- pheno.tca is 63 x 1 dataframe designating which exposure group each sample corresponds to 
-  refactor.mdl.chagas$scores is a 63 x 6 containing the results of the ReFactor adjustment 

In order to find my tensor estimates I used: 

`tensor.mdl.hit <- tensor(tca.mdl = tca.mdl.chagas.2,
                         X = beta.values[hits.joint,,drop=F])`

where: 

- tca.mdl.chagas.2 is the resulting list from the above TCA call 
- beta.values[hits.joint,,drop=F]) are just the beta values associated with the significant CpGs found during a joint test of significance 

the error I receive is: 

INFO [2022-07-05 20:19:39] Validating input...
INFO [2022-07-05 20:19:39] Starting tensor for estimating Z...
INFO [2022-07-05 20:19:39] Estimate tensor...
Error in X - tcrossprod(C2, deltas_hat) : non-conformable arrays

**Comment by E-R** [comment]
The `tca.mdl` argument is "The value returned by applying the function tca to X." (per the documentation of `tensor`). In your case `X` is a subset of the matrix which was used for fitting the model in `tca.mdl.chagas.2`so the dimensions don't match. You can either learn the tensor for the full data matrix and then subset the CpGs you're interested in, or alternatively, you can learn a new model via `tca` for the CpGs in `hits.joint` only and then provide that model to your existing `tensor` call.

**Comment by hdesale2408** [comment]
Thank you!   In the resulting `tensor.mdl.hit` list, are the elements then referring to the estimated cell types?

**Comment by E-R** [comment]
sorry, I missed this somehow.  Per the documentation,`tensor.mdl.hit` will be the estimated cell-type level methylation.
