### ISSUE TITLE
error returned by tca function

### ISSUE THREAD

**Issue by xinming-an** [cozygene/TCA#18]
Got the following error from tca function. Not sure whether this is due to issues with the data or a bug of the pacakge. Thank you for look into this. 

> tca.ptsd.m3 <- tca(X = tca.x,
+                       W = tca.w,
+                       C1 = tca.c1,
+                       C2 = tca.c2,
+                       constrain_mu = TRUE,debug=TRUE)
INFO [2023-09-22 10:34:12] Starting tca...
INFO [2023-09-22 10:34:12] Validating input...
DEBUG [2023-09-22 10:34:12] Validating input types...
DEBUG [2023-09-22 10:34:12] Validating input stucture and values...
DEBUG [2023-09-22 10:34:12] Validating input conditions...
DEBUG [2023-09-22 10:34:12] Validating matrix dimensions...
DEBUG [2023-09-22 10:34:12] Validating the order of observations across matrices...
DEBUG [2023-09-22 10:34:12] Validating that W is non-negative and each row sums up to 1...
INFO [2023-09-22 10:34:16] Fitting the TCA model...
DEBUG [2023-09-22 10:34:16] Starting function 'tca.fit'...
INFO [2023-09-22 10:34:16] Fitting means and variances...
DEBUG [2023-09-22 10:34:16] Starting function 'tca.fit_means_vars'...
INFO [2023-09-22 10:34:16] Iteration 1 out of 10 internal iterations...
DEBUG [2023-09-22 10:34:16] Calculate W_norms and related quantities
DEBUG [2023-09-22 10:34:17] Estimate mus, deltas, gammas.
  |                                                  |   0%Error in quadprog::solve.QP(Dmat, dvec, t(Amat), bvec, meq = meq) :
  matrix D in quadratic function is not positive definite!

**Comment by E-R** [comment]
First, you want to make sure that the number of samples is larger than the number of columns in `C2` plus the number of columns in `C1` times k, where k is the number of cell types you model. Ideally you want the number of samples to be substantially larger than this number (say at least 10 times larger).

Second, you need to make sure that the covariates in your `C1` and `C2` are not linearly dependent in each other; in other words, you want to make sure to remove redundant covariates that can be perfectly explained by a linear combination of the remaining covariates. You can easily check if that's the case in your data by running the `rankMatrix` function (`Matrix` library) on the concatenation of your `C1` and `C2`. If the rank is lower than the sum of the number of columns in `C1` and the number of columns in `C2` then you have redundant covariates that you would need to remove in order for TCA to work.

**Comment by xinming-an** [comment]
Thank you for the quick response. The rank of the covariates matrix (c1+c2) equal to the number of columns so I don't think there is no linear dependence. 

For my case, k=6 and number of columns in c1 and c2 is 14,  and sample size is 616 which is not 10 time larger than 14*6, but I cannot increase the sample size. In the tutorial, you also recommended removing cell types that have very low proportions across all subject. I wonder what cutoff shall I use. below are the mean proportions for the 6 cell type. Shall I remove any of them? 

CD8T     CD4T    NK          Bcell       Mono       Gran 
0.0411   0.154    0.0105   0.0409.   0.0679     0.6851

**Comment by E-R** [comment]
If the number of columns in C1 is p1 and the number of columns in C2 is p2 then ideally you want your sample size to be at least 10 times larger than p2+p1*k.  The model is still valid if this ratio is not kept but power will be lower.

The error you got is most likely related to one (or more) of your covariates. Since the code terminates very quickly after execution I would remove one of the covariates and then run the `tca` function. Repeat this several times, ever time exclude a different covariate. Can you find a covariate that leads to this error? which covariate is it?

Given the mean proportions, it may be wise to exclude NK cells from your analysis if this makes sense in your application. Make sure to normalize the proportions to sum up to 1 for each sample after the exclusion.

**Comment by xinming-an** [comment]
Thank you. The problem was caused by the two batch variables. I checked the two batch variables (batch1 and batch2) in the example data and found out that some subjects do not belong to any of the two batches. For my case, each individual must belong to one of the two batches, so the two batch variables are mutually exclusive. Should I use one variable to indicate the two batches?

**Comment by E-R** [comment]
right, if each sample is coming from either batch 1 or 2 then you want to add just one indicator variable (i.e., 0/1) for whether each sample belongs to batch 1 (or batch 2).
