### ISSUE TITLE
why TCA models always converge after 2 iterations

### ISSUE THREAD

**Issue by humengying0907** [cozygene/TCA#23]
I noticed that the converge condition for `tca.fit_means_vars()` function is set to `ll_diff < 0.001*abs(ll_new)`
(https://github.com/cozygene/TCA/blob/master/R/model_fit.R#L333), in this case it seems that this condition will always be true after the first 2 iterations.

Is there a reason to set `ll_diff < 0.001*abs(ll_new)`? Or should we be expecting '`ll_diff < 0.001`?

**Comment by E-R** [comment]
The choice of 0.001 was arbitrary. Any sufficiently small number should be fine. The reason for adding `abs` is because the likelihood is not guaranteed to decrease unless we prove the objective is convex. On my end, I had runs that required 2 iterations and others that required 3 iterations.
