### ISSUE TITLE
Getting error while running tca.fit function

### ISSUE THREAD

**Issue by skatrinli** [cozygene/TCA#3]
I keep getting an error while running tca.fit function for estimating sigmas. I run debugging and trace the error. Apparently it's something to do with nloptr function. Please see below:

`> tca.mdl <- tca(X = cpg, W = cellTypes, C1 = covars, parallel = F, log_file = "GTP_noob_TCA.log", debug = T)
INFO [2019-10-11 16:45:46] Starting tca...
INFO [2019-10-11 16:45:49] Validating input...
DEBUG [2019-10-11 16:45:49] Validating input types...
DEBUG [2019-10-11 16:45:49] Validating input stucture and values...
DEBUG [2019-10-11 16:45:49] Validating input conditions...
DEBUG [2019-10-11 16:45:49] Validating matrix dimensions...
DEBUG [2019-10-11 16:45:49] Validating the order of observations across matrices...
DEBUG [2019-10-11 16:45:49] Validating that W is non-negative and each row sums up to 1...
INFO [2019-10-11 16:45:52] Fitting the TCA model...
DEBUG [2019-10-11 16:45:52] Starting function 'tca.fit'...
INFO [2019-10-11 16:45:52] Fitting means and variances...
DEBUG [2019-10-11 16:45:52] Starting function 'tca.fit_means_vars'...
INFO [2019-10-11 16:45:53] Iteration 1 out of 10 internal iterations...
DEBUG [2019-10-11 16:45:54] Calculate W_norms and related quantities
DEBUG [2019-10-11 16:45:57] Estimate mus, deltas, gammas.
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100%
DEBUG [2019-10-11 16:51:23] Get initial estimates of sigmas
DEBUG [2019-10-11 16:51:26] Estimate sigmas.
  |++++++++++                                        |  20%
 Error in is.nloptr(ret) : at least one element in x0 < lb 
9.
stop("at least one element in x0 < lb") 
8.
is.nloptr(ret) 
7.
nloptr(x0 = sigmas_hat[j, ], eval_f = function(x, U_j, W_squared, 
    const, tau_hat) minus_log_likelihood_sigmas(x, U_j, W_squared, 
    const, tau_hat), lb = lb, ub = ub, opts = nloptr_opts, U_j = U[, 
    j], W_squared = W_squared, const = const, tau_hat = tau_hat) 
6.
FUN(X[[i]], ...) 
5.
lapply(X[Split[[i]]], FUN, ...) 
4.
pblapply(1:m, function(j) nloptr(x0 = sigmas_hat[j, ], eval_f = function(x, 
    U_j, W_squared, const, tau_hat) minus_log_likelihood_sigmas(x, 
    U_j, W_squared, const, tau_hat), lb = lb, ub = ub, opts = nloptr_opts, 
    U_j = U[, j], W_squared = W_squared, const = const, tau_hat = tau_hat)$solution,  ... 
3.
tca.fit_means_vars(X, W, mus_hat, sigmas_hat, tau_hat, C2, deltas_hat, 
    C1, gammas_hat, max_iters, parallel, num_cores) 
2.
tca.fit(X, W, C1, C2, refit_W = FALSE, parallel, num_cores, max_iters) at <tmp>#49
1.
tca(X = cpg, W = cellTypes, C1 = covars, parallel = F, log_file = "GTP_noob_TCA.log", 
    debug = T) `

**Comment by johnsonzychen** [comment]
Hi, 

Reading a little bit more into the error message, it is complaining that "at least one element in x0<lb", meaning that sigmas is lower than the lower bound. Adding another preprocessing step (filtering out features that have low variance or variance close to 0 across your samples) before feeding that data to TCA should address this issue.

**Comment by E-R** [comment]
@Zeyuan-Chen is probably right. There's a lower bound for the variance of a feature (it's approximately 10^-8; such a lower bound is required for the stability of nloptr and the way TCA uses it). It's most likely the case that one or more of your features have no variance (i.e. the same value for all samples). @skatrinli can you confirm that removing such features (which are btw uninteresting for analysis in any case) solves the problem?

**Comment by skatrinli** [comment]
Thanks!! I tried with a subset of highly variant features (var > 0.01) for the computational sake and it worked. That should be the problem. Also I used ComBat adjusted data (and did not define anything for C2 parameter of tca function), maybe instead of using that I'll use not adjusted data and include chip and array as batch effect in C2. So that I'll have more variability!!

**Comment by E-R** [comment]
Great.
Just note that var > 0.01 might be a stringent threshold, depending on your goal. In any case, my guess is that you have one or more constant features (for which you have the same value across all samples) that remain constant after applying ComBat. Non-constant features are unlikely to have variance below 10^-8. Bottom line: if you wish to use ComBat you can still do so, just remove the (non-informative) constant sites as a preprocessing step (or apply a more stringent threshold for the variance in case your type of analysis requires so).
