### ISSUE TITLE
TCA error

### ISSUE THREAD

**Issue by jvsandoval** [cozygene/TCA#4]
Hi,
I got the following error when I used the tensor function:

7 nodes produced errors; first error: system is computationally singular: reciprocal condition number = 3.18896e-17

I thought that this error was because of ram memory, so I decided to use a high performance computing service to analyze the data using 8 processors and 4 GB per processors, and I got the same error.

This is the command line that I used:
 tca.mdl <- tca(X = X, W = W, C1 = NULL, C2 = NULL, parallel = TRUE, log_file = paste("v1_RefFree_7cell_", d, ".log", sep = ""), debug = T)

Z_hat <- tensor(X = X, tca.mdl, log_file = paste("v1_RefFree_7cell_", d, "_2.log", sep = ""), parallel = T, debug = T)

The data set that I am analyzing is a matrix of 736432 probes and 100 samples. Cell-type-specific matrix was obtained using GLINT program with Houseman option. In this analysis, I did not include any design matrices.

Do you have any idea what could be happening?

Thank you,

Jose Sandoval
log file tca function: v1_RefFree_7cell_2019-10-24.log
log file tensor function: v1_RefFree_7cell_2019-10-24_2.log

[v1_RefFree_7cell_2019-10-24.log](https://github.com/cozygene/TCA/files/3772572/v1_RefFree_7cell_2019-10-24.log)

[v1_RefFree_7cell_2019-10-24_2.log](https://github.com/cozygene/TCA/files/3772573/v1_RefFree_7cell_2019-10-24_2.log)

**Comment by E-R** [comment]
I believe the error is related to the matrix inversion that is performed by the 'tensor' function. Did you exclude features that are constant across your 100 samples? Specifically, I would recommend filtering out features with variance less than 10^-8.

If adding this filter doesn't work - do you still get an error when running the same tensor command on a small subset of the data? (e.g., the first 100 features)? Note that for doing so you will need to subset the tca.mdl object (see function 'tcasub')

**Comment by E-R** [comment]
Closed due to inactivity
