### ISSUE TITLE
tcareg analysis wih quantitative data

### ISSUE THREAD

**Issue by antgomo** [cozygene/TCA#7]
it is possible to run tcareg using quantitative trait (numerical) as a phenotype, i.e Age, instead the classical factor level 0/1 

tcareg(X, tca.mdl, y, C3 = NULL, test = "marginal",
  null_model = NULL, alternative_model = NULL, save_results = TRUE,
  output = "TCA", sort_results = TRUE, parallel = FALSE,
  num_cores = NULL, log_file = "TCA.log", features_metadata = NULL,
  debug = FALSE)

**Comment by E-R** [comment]
Yes. In fact, 'tcareg' is designed for quantitative phenotypes. From a statistical perspective, it is not theoretically justified to use binary phenotypes under the tcareg model, however, it works well in practice.
