### ISSUE TITLE
Beta methylation values from tensor problems

### ISSUE THREAD

**Issue by antgomo** [cozygene/TCA#8]
I am using tensor function to get beta methylation values of each cell type to then make a heatmap using the results from tcareg

Here is my pipeline:

res<- tcareg(X = betas, tca.mdl = tca.mdl, y = y,
              test = "custom", null_model = NULL, alternative_model =colnames(cell_comp2.scaled)[1],
              C3 = wk0[,c("Sex","Age")],
              save_results = F,
              log_file = "tcareg.log",parallel = T,num_cores = 20)

 my.res<-as.data.frame(rownames(betas)[which(res$pvals<.05)])
     my.res$pval<-res$pvals[res$pvals<.05]
  colnames(my.res)[1]<-"CpG"
  rownames(my.res)<-my.res$CpG
  my.res<-merge(my.res,meth.sites,by="row.names")
  my.res<-my.res[,-1]

##subset the estimates of the model parameters
mdl.tca.sub <- tcasub(tca.mdl, features = rownames(betas), log_file = "F.tcasub.log")

###estimate cell-type-specific methylation for the associated site
Z_hat <- tensor(X = betas, mdl.tca.sub, log_file = "F.tensor.log")

then, plot heatmap using 

data3<-Z_hat.plot[[6]][rownames(Z_hat.plot[[6]]) %in% res.island$CpG,]

What i am seeing, is if I plot a boxplot for each Cpg, i can see the differences between groups while if i am plotting all the signifficant results, pval<0.05, i cant'see the split of the groups.

Maybe I am doing some thing wrong?

Thanks in advance

**Comment by E-R** [comment]
First, can you please clarify what is it that you are trying to do and what is your goal?

Second, the definition of some of the variables that you refer to is not shown in your code snippet, please attach the complete code.

**Comment by antgomo** [comment]
Hi,

my goal is to plot in a heatmap the differences between control and classes that i got from tcareg, i.e plot in a heatmap how these cpgs are separating my controls from cases

So, following your code, if i want to plot the differences from tcareg cases vs controls in cd4:

cd4 <- colnames(W)[1] # the first column in W corresponds to CD4
res <- tcareg(X = X, tca.mdl = tca.mdl, y = y, C3 = C3,
              test = "custom", null_model = NULL, alternative_model = c(cd4),
              save_results = TRUE, output = "GSE42861.tcareg.CD4",
              log_file = "GSE42861.tcareg.log",
              features_metadata = "HumanMethylationSites.txt")

#get hits position in beta matrix
hits<-rownames(X)[which(res$pvals<0.05)]

# subset the estimates of the model parameters
mdl.tca.sub <- tcasub(tca.mdl, features = hits, log_file = "GSE42861.tcasub.log")
# estimate cell-type-specific methylation for the associated sites

Z_hat <- tensor(X = X[hits,], mdl.tca.sub, log_file = "GSE42861.tensor.log")

cd4 <- Z_hat[[1]] # the first column in W is CD4, therefore take the first element in Z_hat


#try to plot differences in heatmap

library(RColorBrewer)
library(gplots)

y <- as.matrix(covars[,5])#3phenotype


# normalise and scale the data
data <- t(scale(t(cd4))) # z-score normalise each row (feature)
data <- apply(data, 2, function(x) ifelse(x > 4, 4, x)) # compress data within range
data <- apply(data, 2, function(x) ifelse(x < -4, -4, x)) # compress data within range


library(heatmap.2x)## approach

spcol<-as.vector(ifelse(y==1,"red","blue1"))##case red, control blue

cols <- colorRampPalette(brewer.pal(10, "RdBu"))(256)

heatmap.2x(data, col=rev(cols), Colv = NA,Rowv=TRUE, scale="none", ColSideColors=spcol,
           trace="none", dendrogram="both", 
           cexRow=1, cexCol=1.4,
           main="CD4 case vs control",
           labCol=NA,labRow=NA, density.info="none",
           hclust=function(x) hclust(x,method="complete"),
           distfun=function(x) as.dist((1-cor(t(x)))/2)
           
)


The heatmap that i got, is not splitting me the cases and controls, i can see differences in boxplot for each cpg, but when i try to see these differences case vs controls in a classical heatmap, i couldn't see

**Comment by E-R** [comment]
You can do something like this:
`
require("gplots");
heatmap.2(cd4[,c(which(y==1),which(y==0))],Colv = FALSE)
`
which will sort the columns (samples) by the case/control status and create a hierarchical clustering of the features.

Note that if you're using the data in the vignette then you shouldn't expect to see significant changes between cases and controls because the data in the vignette was designed to include only a single feature that is significantly different between cases and controls. Also, note that if you have many features then most features with p-value<0.05 will be false positives and then I believe the heatmap would not reflect the kind of information that you are after. I would recommend using a more stringent threshold for this purpose (e.g., you can use FDR).

**Comment by antgomo** [comment]
Well, i was thinking same as you, i subset using qval< 0.05, but more or less similar result

Then, the idea is to apply stringent thresholds, isn't it?

Another quesion, when I ru these two lines

mdl.tca.sub <- tcasub(tca.mdl, features = hits, log_file = "GSE42861.tcasub.log")
Z_hat <- tensor(X = X[hits,], mdl.tca.sub, log_file = "GSE42861.tensor.log")

Must i do it only for hits, aka results qval<0.05, or Must i run for all the Cpgs and then subset for the hits?
Which is the difference?
