### ISSUE TITLE
cell-type-specific methylation for associated sites

### ISSUE THREAD

**Issue by antgomo** [cozygene/TCA#9]
Hi,

i am using tcasub and tensor to get the cell-type-specific methylation for a set of associated sites for plot purposes

I am following this

    ##subset the estimates of the model parameters
    mdl.tca.sub <- tcasub(tca.mdl, features = rownames(betas.test), log_file = paste0(imid,".tcasub.log"))

    # estimate cell-type-specific methylation for the associated site

    Z_hat <- tensor(X = betas.test[my.sel.sites,], mdl.tca.sub, log_file=paste0(imid,".tensor.log"),parallel=T,num_cores=5)

My question is, if I ran previously tca for tca.mdlwith sex and age as a covariates, the cell-type-specific-methylation for this sites will be adjusted for sex and age, or do i have to adjust later? i.e, the signal contains still sex and age or not?

Thanks in advance

**Comment by E-R** [comment]
The 'tensor' function uses the covariates in your tca model (tca.mdl) when estimating the cell-type-specific levels, so the values are not adjusted for these covariates. It means that if you want to use Z_hat in a down-stream analysis then you should adjust for these covariates if appropriate.
